### ISSUE TITLE
Allow unicode/custom characters for lines/boxes/arrows, for both rendering and output

### ISSUE THREAD

**Issue by mreinstein** [lewish/asciiflow#143]
rather than:

```
+------+
|      |
|      |
+------+
```

give me:

```
┌------┐
|      |
|      |
└------┘
```

**Comment by iJunkie22** [comment]
Doing so would break the basis of standard 0-128 ASCII text. At this rate, you may as well use full box-drawing unicode.

```
┌──────┐
│      │
│      │
└──────┘
```

Note that this makes the app useless for programmers using non unicode/UTF encodings (ASCII, Latin-1, CP1252/ANSI). For this reason, I suggest this *feature* be an ***option***.

**Comment by mreinstein** [comment]
but the you agree; nicer looking boxes please :)

**Comment by Qix-** [comment]
This is an option already, though it's just for rendering. You can't save them as box-drawing characters. This is something I plan to support in Asciiflow 3 when I get the chance to finish it (I know, it's been a very, very long time since I started on it - life has taken me on a bit of an adventure and I'm just now getting back into OSS).

**Comment by mreinstein** [comment]
> though it's just for rendering

Yeah, but for me the tool is only a necessary step to generate the output. I want nice looking boxes on output, because that's what others see. One of my use cases is embedding sweet ascii diagrams in source code. Like this:

```
/*
a re-usable product hero image module.

                         ●
                         |
                      ┌--┴---------┐
                      |initializing|
                      └---┬--------┘
                        READY
                          |
                          ▼
      ┌-------┐-HIDE-▶┌------┐
   ┌--┤showing|       |hidden├--┐
   |  └-------┘◀-SHOW-└------┘  |
   |        ▲          ▲        |
   |        |          |        |
MUTATION   SHOW       HIDE   MUTATION
   |       ┌┴----------┴┐       |
   └------▶|  mutating  |◀------┘
           └------------┘
*/

```

I used to generate the initial versions with ascii flow, and then clean up the output to have nicer looking ascii.
 

> This is something I plan to support in Asciiflow 3 when I get the chance to finish it

Whoa, this is super exciting to hear about! I'd love to hear more details. Personally, I've got a very small spinoff project, which is less of a general ascii drawing tool and more focused on producing finite state machine like diagrams (labled boxes with connected directional lines.) Things that i really wanted which ascii flow currently lacks:
* crisp (not blurred/anti-aliased) font rendering in the editor
* nicer looking ascii output
* a hyper minimal editing experience
* keyboard shortcuts
* editor architecture: structure the editor's implementation around finite state machines. It has a fairly robust hierarchical fsm which has done wonders to keep the codebase clean.

Here is my take on this:   https://github.com/mreinstein/ascii-diagrams

and you can see a rough prototype running: http://ascii-diagrams-hmlcqarvkp.now.sh/

Maybe at some point we could put our heads together and see if there's any overlap, if you find any of this stuff appealing.


> life has taken me on a bit of an adventure and I'm just now getting back into OSS

Well let me be the first to say, welcome back! Your software has inspired me, and other people I'm sure! It's wonderful to have you back among our ranks. :-)

**Comment by lewish** [comment]
> Maybe at some point we could put our heads together and see if there's any overlap, if you find any of this stuff appealing.

Hello! I'm back. Love what you've done here, and I've tried to incorporate some of the ideas into thew new version of asciiflow now. I think it's much closer to your vision, but still some things missing probably. Given the new release, I'm keen to discuss how we can incorporate more of this!

**Comment by mreinstein** [comment]
Welcome back! Would be happy to discuss and see what you've got. :-)

**Comment by mehmetalianil** [comment]
I see that this can be achieved with selecting ASCII Extended on export now. 
![image](https://user-images.githubusercontent.com/551129/188490548-5ed57737-3f86-4ec0-be4e-03a470c39ec7.png)
