### ISSUE TITLE
Asciiflow + Privacy

### ISSUE THREAD

**Issue by Qix-** [lewish/asciiflow#154]
I'd like to open a discussion with users about privacy and Google/tracking/etc.

I understand some people do not want Google integrations on certain pages because of the "Big Brother" effect; however, e.g. Google Drive integration is undoubtedly a feature people want and use.

Keeping in mind this will be a **statically served** web-application from Google pages, what is the appropriate action here?

Here are a few suggestions:

- All third-party scripts are loaded conditionally (using javascript) based on the [Do-Not-Track setting being preset or not](https://dev.to/corbindavenport/how-to-correctly-check-for-do-not-track-with-javascript-135d).
- There is a `/lite` path that you can visit that is a specially built version of the app sans all third-party integrations.
- We simply drop all Google functionality in lieu of Gist/permalink support (things have changed in the last ~6-7 years in terms of what tools people are using).

Let me know what you think. The discussion here will affect Asciiflow 3 (AF3) exclusively; the existing version will not be updated to reflect any decisions made.

**Comment by leo-lb** [comment]
I propose that you find replacements for the nonfree services that are promoted through ASCII Flow. It should be possible to support WebDAV and support most free (as opposed to nonfree) services.

**Comment by Qix-** [comment]
Is there a way to use a common open standard to interact with non-free services on an opt-in basis, though?

**Comment by leo-lb** [comment]
@Qix- No because Google Drive doesnt support WebDAV. Blame them.

**Comment by leo-lb** [comment]
@Qix- 

I additionnally propose that all tracking scripts are unconditionally removed, they are unethical pieces of code.

**Comment by leo-lb** [comment]
It is especially relevant since the project is under the GPLv3 - it can't be combined with these proprietary tracking softwares legally.

**Comment by Qix-** [comment]
Understood; AF3 might be relicensed though. Tracking software will be removed anyway, though since it's hosted via GitHub pages there's no way to disable that tracking.

Also, please edit comments instead of double posting in the future :slightly_smiling_face:

**Comment by leo-lb** [comment]
@Qix- 

I came across this: https://officejs.nexedi.com/ and https://jio.nexedi.com/

This is interesting for you because it is a platform that would allow you to support several storage backends like locally in the browser, webdav, dropbox, google drive and anything else implemented in the future with a single API.

**Comment by Qix-** [comment]
That's great but I don't see how that pertains to the topic of privacy in particular. Google Drive support can already be achieved without installing Google scripts on the page.

**Comment by leo-lb** [comment]
@Qix- 

If it was only about me, local browser storage and webdav is sufficient, but that's you who wanted Google Drive to remain, so I'm sharing with you something that can abstract both at the same time.

**Comment by lewish** [comment]
Chiming in here:

- New version is now without Google integration, relying on local storage instead
- All tracking scripts removed currently
- License changed to MIT

From a product perspective, I'd like to continue to use Google Analytics so I can understand user behaviour. Given that, I propose we do as @Qix- proposed and conditionally load this script based on the do-not-track status.

**Comment by Bill-ColeUS** [comment]
My vote, is to avoid google as much as possible.

A simple import/export via copy/paste is enough to cover most cases, but having 3rd party tools is ok, as long as they don't load external files, or they are optional and only load when used.

btw, was the *import* functionality removed in the new version? I can't see how to paste something...

**Comment by lewish** [comment]
Closing this now, as there hasn't been tracking for a while and I have no plans to add it.
