### ISSUE TITLE
[Feature] - Pre-Defined Shapes; Flow Chart

### ISSUE THREAD

**Issue by HotDenim** [lewish/asciiflow#157]
Can you have option to draw pre-defined Shapes, like used in flow-charts and other shapes also. 

E.g. Click an icon to select a shape, say Rectangle, which then prompts you to the Text for  inside the rectangle, also allowing the adjustment of the options;  size / dimensions / scale, border thichkness, Auto Resize To Text, while confirming to create the shape, and then allowing it to be put down onto a position on the canvas.

**Comment by Qix-** [comment]
Hey! Sorry for the delay here. While some of the text considerations are on our radar, there unfortunately isn't much in the way of unicode support for non-rectangle shapes that could be useful for Asciiflow in particular.

Thanks for the suggestion though! :)
