### ISSUE TITLE
Copy/Paste is not working

### ISSUE THREAD

**Issue by pavkr** [lewish/asciiflow#172]
Reproduce: 
 1. create an object
 2. select, copy then paste
 4. create another object
 5. select, copy then paste
 
result: the first object is pasted 

Note: sometimes you don't have to do it twice (for example if you already have something in the buffer)

**Comment by pavkr** [comment]
I'll say it here: you fucked up a lot of things with the new release. I loved the previous version of the tool, and this one made me yell in my head very bad things about its creator... I'd love you would refrain from breaking what's working. If there is a way to rollout or to use the previous version, please, help me to find out how. Very shitty of you to leave it as it is. Cheers mate!

**Comment by eschie** [comment]
text paste also not working
