### ISSUE TITLE
[Bug] Copy/Paste not working in FireFox

### ISSUE THREAD

**Issue by cruscio** [lewish/asciiflow#174]
Firefox: Draw a square. Select it. Ctrl-C / Ctrl-V - and the text that was previously in the clipboard is pasted, not the square. 
Same action worked fine after switching to Chrome.

Firefox 86.0 (64-bit) on Windows 10

**Comment by Qix-** [comment]
Please search a bit next time :)

Duplicate of #172.

**Comment by cruscio** [comment]
@Qix- I [did](https://github.com/lewish/asciiflow/search?q=firefox&type=issues) - there were 6 results, none of them seemed related. I wasn't able to reproduce the issue in another browser, so I figured searching for FF was adequate. Apologies for the trouble.
