### ISSUE TITLE
New special characters in new version

### ISSUE THREAD

**Issue by KUGA2** [lewish/asciiflow#179]
You updated the page recently. While i appreciate the new layout and help in the sidebar, the new version adds special characters.

Compare:
New:
![image](https://user-images.githubusercontent.com/10581931/110477249-3b8d9c80-80e3-11eb-8783-d9982f228dfa.png)
https://asciiflow.com/#/

Old
![image](https://user-images.githubusercontent.com/10581931/110477226-34668e80-80e3-11eb-82b6-04964fc70b2a.png)
https://asciiflow.com/legacy/

There are new arrow symbols and new box corners. This looks better but has more portability issues.
We have multi platform development and need to change the encoding of text files often. I am scared, that changing those characters back and forth in encoding will eventually break our diagrams.

Could you provide a mode to import/export the diagram with the old characters?
Also please keep the legacy mode alive as long as this is not in latest.

Btw: Thanks for you tool :)

**Comment by Qix-** [comment]
![image](https://user-images.githubusercontent.com/885648/110483253-d4bfb180-80e9-11eb-8e39-f52b7a1366e1.png)

😉

**Comment by KUGA2** [comment]
Oops, my bad.

I cannot find the import. Was this removed?
