### ISSUE TITLE
Importing a diagram with the new version?

### ISSUE THREAD

**Issue by martinbonnin** [lewish/asciiflow#182]
Hi 👋 ! 

Huge fan here, the new version looks sleek but I haven't found a way to import a block of text?

I guess being able to copy/paste text is general would also work for import. Or do I miss something?

**Comment by lewish** [comment]
You're not missing anything! There is no import, but this wasn't a completely deliberate oversight.

Copy pasting should allow you to pull diagrams back in to the web app from other places, however I appreciate this isn't great if you've exported with comment blocks, or changed the encoding to basic ASCII for example.

Can you let me know what you would like from an import tool that the copy-paste functionality doesn't cover?

**Comment by martinbonnin** [comment]
Aaaaahh, I just got it! Looks like I need to be in "Selection" mode to copy-paste? I was somehow trying in "Text" mode.

> Can you let me know what you would like from an import tool that the copy-paste functionality doesn't cover?

Copy-paste is perfect. I guess I was mainly disoriented by the fact that there used to be an import option but Ctrl-C Ctrl-V works very well for my use case, it's all good 👍 . Maybe allow pasting in Text mode too?

**Comment by lewish** [comment]
Yup makes sense! One would expect copy-paste to work regardles of tool selection, so let me fix that. :+1:

**Comment by antoineco** [comment]
@solyarisoftware `Ctrl-V` works, as long as you are in `Select & Move` mode.

![image](https://user-images.githubusercontent.com/3299086/132726966-25aa2eb2-472c-433e-98e2-71de33eb7a90.png)

**Comment by solyarisoftware** [comment]
oh! me stupid, It works as you say. Thanks  @antoineco !

**Comment by pstackle** [comment]
I would also suggest adding back an "import" button. The current behavior is not very discoverable and I ended up on this github issue after having to google for how to import a diagram i had created on the previous version.

Having an "import" button right alongside the "export" button would provide the needed discoverability and when clicked, it could be as simple as a message explaining to paste using the keyboard shortcut.

**Comment by codec-abc** [comment]
Got bitten by that too. The copy/paste behavior is rather uncommon and I bet a decent numbers of users would come here to understand how to copy/paste into the application. Otherwise it is pretty dope!

**Comment by jensljungblad** [comment]
Also got confused by this. Actually did try pasting but wasn't in select mode. Adding a button just for discoverability would be nice 👍

**Comment by dpkn** [comment]
same hahaha

**Comment by lewish** [comment]
Fixed in #280
