### ISSUE TITLE
erase option is missing in latest asciiflow diagrams

### ISSUE THREAD

**Issue by adisheshsm** [lewish/asciiflow#183]
Hi,

earlier versions had erase option. 
is it possible to include erase option in this latest version?

Select and Move option is not sufficient in some cases to edit the existing diagram.

Thanks and regards,
Adishesh

**Comment by adisheshsm** [comment]
Hi Lewish,

i tried select and backspace/delete key, delete is not working. 
for now i switched to https://asciiflow.com/legacy/ 


Thanks and regards,
Adishesh

**Comment by ComFreek** [comment]
> Hi - Using the select tool and then pressing delete or backspace should do exactly the same as the old erase tool

This worked. But I've spent at least 2-3 minutes figuring this out and for finding this issue. Maybe the UX could be improved somehow.
