### ISSUE TITLE
Freeform: pick from built in characters (`─`,`┐`, etc)

### ISSUE THREAD

**Issue by jtagcat** [lewish/asciiflow#198]

**Comment by ade-sede** [comment]
Tried implementing this.
The [PR](https://github.com/lewish/asciiflow/pull/213) here.

**Comment by jtagcat** [comment]
jfyi you can write 'Fixes #198' or 'Closes #198' in the commit, or the description of the PR.

**Comment by ade-sede** [comment]
> jfyi you can write 'Fixes #198' or 'Closes #198' in the commit, or the description of the PR.

Thanks ;) will do next time 😊
