### ISSUE TITLE
Drawing: don't merge with neibghouring objects

### ISSUE THREAD

**Issue by jtagcat** [lewish/asciiflow#199]
<table>
<tr>
	<td>Current
	<td>Desired
<tr>
	<td><img src="https://user-images.githubusercontent.com/38327267/120071946-df526d00-c080-11eb-9c8c-6dbe34c197f6.png">
	<td><img src="https://user-images.githubusercontent.com/38327267/120072008-27718f80-c081-11eb-99c9-dd7826498fc9.png">
</table>

**Comment by slymz** [comment]
E.g. two simple boxes can not be drawn side-by-side:

```
┌────┐┌────┐
│    ││    │
└────┘└────┘
```
