### ISSUE TITLE
Added Markdown export, CommenType backtick "```"

### ISSUE THREAD

**Issue by zampierilucas** [lewish/asciiflow#206]
When pasting an ASCII diagram to a platform that uses Markdown, such as Github, Gitlab, Notion.  It Is needed to involve the diagram by a code block "```".

Add an option to export the diagram wrapped by the code block syntax.

Probably something like:
**/client/export.tsx**
```typescript
  <MenuItem value={"code_block"}>
    Standard multi-line <CommentTypeChip label="``` ```" />
  </MenuItem>
```

**Comment by lewish** [comment]
This is now in!
