### ISSUE TITLE
google drive blocked

### ISSUE THREAD

**Issue by ilcaa72** [lewish/asciiflow#207]
i am trying to use the older Infinity version so i can save to GDrive (i dont see that capability on newer version) BUT the access to connect to google account keeps getting denied.... has this been turned off or it something on my end?

does newer version have ability to connect to a drive to reuse/edit drawings?

**Comment by lewish** [comment]
I'm afraid the Google Drive integration has not worked for a long time - the new version stores drawings, but only within local storage! 

No plans to fix this any time soon, I'm afraid.

Note that - you can export a drawing to a shareable URL that you can hold on to to move between people / computers, as a partial workaround.
