### ISSUE TITLE
Pressing backspace when editing text on Firefox go to previous page

### ISSUE THREAD

**Issue by fabriziobertocci** [lewish/asciiflow#216]
Well as I said on the title, instead of deleting the last typed character, when you press backspace on Firefox, it goes back to the previous page.
Chrome works fine.
Tested on Firefox 93.0 on Linux Mint 20.2

**Comment by Akiyamka** [comment]
Firefox 95.0.2 on Fedora 34 - works just fine

**Comment by fabriziobertocci** [comment]
ah... weird, It must be some interaction with the window manager then. I just tested again on my machine, problem is still there: pressing backspace, it deletes one character but then the browser go back to the previous page. 
Firefox 95.0.1, Linux Mint 20.2

**Comment by Semnodime** [comment]
The issue can be reproduced using this configuration:
`https://asciiflow.com/` on `Firefox 96.0+linuxmint1+una` (without any addons) / `Linux Mint 20.3 (Una)`:

Pressing <kbd>backspace</kbd> navigates to the previously visited site.

**Comment by Mxrcon** [comment]
I'm using `firefox 99+linuxmint1+una` on `linux Mint 20.3` and still able to reproduce this error. Sadly, this makes the usage really hard.

**Comment by Akiyamka** [comment]
> ah... weird, It must be some interaction with the window manager then. I just tested again on my machine, problem is still there: pressing backspace, it deletes one character but then the browser go back to the previous page. Firefox 95.0.1, Linux Mint 20.2

I have gnome environment and X11

**Comment by bellgab** [comment]
Hi!
Go to about:config page (carefully)
Set the
browser.backspace_action value to 2!
restart.
This worked for me.

**Comment by J0sephDavis** [comment]
I am also having this issue.
Mozilla Firefox 120.0.1
OS: Linux Mint 20.3 x86_65
DE: Cinnamon
WM: Mutter

**Comment by lewish** [comment]
I've pushed a potential fix, but as I can't actually reproduce this myself, could someone encountering it possibly confirm if this is still an issue? Please re-open if you are still seeing it!

**Comment by fabriziobertocci** [comment]
I just tested on Firefox 123.0 on Linux Mint 21.2 and it works! 
Big thanks!!!
