### ISSUE TITLE
Wrong label for semicolon comments

### ISSUE THREAD

**Issue by myerspliers** [lewish/asciiflow#218]
Two small things in the Download options:
1. Apostrophies is misspelled. It should be Apostrophes.
2. The Semicolon comment type is mislabeled as Apostrophies. 
![image](https://user-images.githubusercontent.com/12052130/141338188-4cbfb901-cf2b-45d3-9fdc-8911343671e7.png)

Some other suggestions:
It might be more natural to use the singular name of the comment character if there is only one character.

Hash `#`  *-- not plural since there is just one character at the beginning of the line*
Slashes `//`     *-- keep the plural since there are two*
Dashes `--`  *-- keep plural*
Apostrophe `'` *-- singular since there is only one on the line*
Backticks multi-line `` ``` ``` ``
Four spaces `␣␣␣␣`   *-- make this wider so it looks like four spaces in a monospaced font - or use the open box (U+2423) character?*
Semicolon `;` *-- singular*

**Comment by lewish** [comment]
Fixed in https://github.com/lewish/asciiflow/pull/214
