### ISSUE TITLE
Right facing arrow along line

### ISSUE THREAD

**Issue by rictic** [lewish/asciiflow#234]
I can make:

```
────◄───
```

But I want to make:

```
────►───
```

However, no matter how I draw it, I seem to always get the left pointing arrow.

**Comment by YodaEmbedding** [comment]
For now, I just draw the wrong arrow and then fix it manually after exporting.

Funnily, importing a diagram with right arrows converts them to left, too...!

**Comment by lewish** [comment]
This should be possible now Since #299
