### ISSUE TITLE
Ability to export drawings to a .txt file

### ISSUE THREAD

**Issue by AreaOfZero** [lewish/asciiflow#235]
I just think it would be a useful feature to have, because sometimes (at least in my use cases) I just need the flow chart and don't necessarily need to paste it into a code file, so being able to immediately download it as a .txt file would be much more convenient then getting the raw text, making a new .txt myself, and then pasting the chart into the file.

Otherwise, this is a great web application that I love to use! Keep up the great work.

**Comment by lewish** [comment]
Sorry I think this is unlikely to happen, I'm not sure how this could be accomplished with asciiflow as a purely client side web app
