### ISSUE TITLE
Rename doesn't function

### ISSUE THREAD

**Issue by jtagcat** [lewish/asciiflow#242]
Rename dialogue has 'Create' button, and it just creates a new blank file.

Expected: 'Rename' button, and file is renamed.

### GitHub Etiquette

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by darkronin** [comment]
Worse than that, I observed that 'Rename' not only creates a new blank file, but also deletes the original (not sure if that depends on having a few files open already)

**Comment by lemon-sh** [comment]
I'm experiencing the same problem here

**Comment by calvinmkissinger** [comment]
Seconded, I renamed my drawing and it disappeared!

**Comment by dschiller** [comment]
Also "S" key is not working: https://github.com/lewish/asciiflow/issues/306

Not sure if this Repo has any QA - wonder as there are so many contributers.
