### ISSUE TITLE
Camera Pan

### ISSUE THREAD

**Issue by L3g3nd4ndM7th** [lewish/asciiflow#269]
I am having trouble finding how to pan the camera. Is the map infinitely sized? I am using chrome OS so that could be part of the problem maybe?

**Comment by lewish** [comment]
Hold `space` to enter panning mode! It's not infinite, but it's very big.

![image](https://github.com/lewish/asciiflow/assets/912458/afb93338-6832-4bad-b1b7-c60628fcc2cc)
