### ISSUE TITLE
Can't Pan on MacOs

### ISSUE THREAD

**Issue by brianhenryhf** [lewish/asciiflow#270]
Hi,

System: MacOS 12.6.5
Browser: Chrome 114.0.5735.198 OR Firefox 115.0.2

From some older issues, I see that panning should be possible via CMD+drag. On the aforementioned system/browser combos, I'm seeing CMD+drag acting the same as drag alone - no panning occurs. This appears true regardless of specific mode i'm in (e.g, select, line, text, etc). Perhaps I'm not working off the latest instructions on how to do this, but it seems like it may be broken.

Thanks for the tool- super-useful.

**Comment by Asc2011** [comment]
I tried and it worked :) use <space> and <hold mouse left>.

**Comment by lewish** [comment]
Holding space enters panning mode, can you check if that works? It should do but reopen if you are still having issues.

![image](https://github.com/lewish/asciiflow/assets/912458/a429e357-eedd-472c-81a1-40793c74c2d2)

**Comment by brianhenryhf** [comment]
space works! Thanks!

**Comment by mleduque** [comment]
Tried everything, space, ctrl+move mouse, nothing seems to work (on macos firefox)
