### ISSUE TITLE
How do I run the app?

### ISSUE THREAD

**Issue by seflless** [lewish/asciiflow#291]
The instructions show how to start the dev server, but not how to run the app so you can see the UX. What am I missing? Should it be opening electron or is there a web page I can see the live coded app on?

Help appreciated, very cool project.

**Comment by lewish** [comment]
The latter - [asciiflow.com](asciiflow.com) !

**Comment by seflless** [comment]
What is the url to open though, it doesn't log a url or port to open or open a web page. That's where I was getting stuck.

**Comment by seflless** [comment]
Ah, figured it out. It's hosted on port 8080 `http://localhost:8080/`.
