### ISSUE TITLE
Dataloss

### ISSUE THREAD

**Issue by dschiller** [lewish/asciiflow#308]
Under certain circumstances - not figured out yet - data is empty after reopening asciiflow. Possibly has to do with the not working Delete first Scene issue.

**Comment by rajrao** [comment]
I had a similar dataloss issue. I was working on a diagram, had opened it over multiple days and everything was good. I renamed the file today and immediately after that, the diagram went away :(

**Comment by lewish** [comment]
Sorry about this! This should now be fixed :)
