### ISSUE TITLE
Moving a box also moves the arrow

### ISSUE THREAD

**Issue by addoyle** [lewish/asciiflow#34]
When moving a box with a normal line attached, the line connector (+) stays still. However, with an arrow line attached, the arrow (<,^,>,V) moves with the box.

```
  +----           +----
  |               |
+-+---+  -->  +---+-+
| Box |       | Box |
+-----+       +-----+
```

vs.

```
  +----           +----
  |               |
+-v---+  -->  +-v-+-+
| Box |       | Box |
+-----+       +-----+
```

**Comment by Qix-** [comment]
Apologies for the noise 5 years later.

Good catch, going to tag this as a bug to make sure the new version doesn't have this issue.

**Comment by lewish** [comment]
This particular case is fixed in the latest version, although there are still some edge cases when moving lines with connected arrows.
