### ISSUE TITLE
Have the ability to load/save file locally or to a git repo

### ISSUE THREAD

**Issue by andrewdavidmackenzie** [lewish/asciiflow#37]
Asciiflow2 looks great for us to use for architecture diagrams of our code and infrastructure.
We'd like to have those diagrams versioned and alongside code in our GIT repos.

I see two ways to enable that:
1) Enable load-from/save-to a local file, which will be a git clone of the repo and then we'll do a Pull-Request to update it.

2) Github integration directly. More complex and maybe less flexible?

BTW: Drive integration is cool, and I use it, but doesn't cover this specific need.

**Comment by Qix-** [comment]
Sorry for the noise 5 years later.

See #150 for a few updates regarding this. Tagging for visibility and to make sure it's addressed in AF3.

**Comment by crazybber** [comment]
also expecting this feature.

**Comment by lewish** [comment]
Local files are now a concept using local storage.

![image](https://user-images.githubusercontent.com/912458/109414415-b6034180-79aa-11eb-82ff-460f814ec7a5.png)

Git integration is a cool idea, but honestly probably completely infeasible as I'd like to keep this client side only. I think the path forward for better git integration is to integrate asciiflow into a tool like vscode and allow you to edit drawings in place in code.

**Comment by Qix-** [comment]
I agree with @lewish here, there isn't much in the way of Git integration aside from perhaps posting to Gist, but that should be its own issue if we wanted to do that.

I'm going to go ahead and close this - if a more specific request comes up, don't hesitate to open a new issue!
