### ISSUE TITLE
Add ditaa preview and export

### ISSUE THREAD

**Issue by zellyn** [lewish/asciiflow#45]
It would be nice to have [ditaa](http://ditaa.sourceforge.net/) preview and export.

**Comment by icarlsen** [comment]
Is there a chance the feature will be added back?

**Comment by Qix-** [comment]
Not sure how this would be done in the browser since it's a Java app but I can see about integrating it with the Electron version.

**Comment by eduardomozart** [comment]
Hello @Qix-, I believe that Ditaa doesn't necessarily needs to be reimplemented, as Ditaa uses ASCII, you only needs to provide new objets forms (like circles, database etc.) presents on Ditaa and when exporting it you can render it externally using PlantUML online that supports Ditaa and provides an API for it OR you can simply provide the TXT file and the user converts it using Ditaa locally.
