### ISSUE TITLE
Capture delete key

### ISSUE THREAD

**Issue by weex** [lewish/asciiflow#56]
After working on a doc for a while, I hit Delete on Chrome on OS X and the browser went back to the previous page losing all of my data. Though connecting to Google Drive is probably a way to protect against this scenario, Google drive permissions are not clear so that's a peripheral issue. I think it'd be good to capture the delete key press or anything that might cause a page reload and put up a confirm box like so many sites these days do.

**Comment by skrap** [comment]
Yup just lost about 5 minutes of work twice via this exact same issue.

Please consider adding a confirmation box!  :'(

**Comment by Qix-** [comment]
Yep, good idea.

**Comment by Hexilee** [comment]
Any progress?

**Comment by lewish** [comment]
This shouldn't be happening any more - or if it does, all drawing state is stored in local storage so you shouldn't lose any progress.

If you manage to create a situation where you are accidentally invoking browser actions pressing del/backspace etc let me know as I can't reproduce on the new version.
