### ISSUE TITLE
Allow adding images as reference guides

### ISSUE THREAD

**Issue by zsoltmar** [lewish/asciiflow#62]
Would be cool if you'd be able to upload an image as a background with adjustable opacity so you can use it as an underlay.

**Comment by Qix-** [comment]
Sorry for the noise 4 years later :)

Interesting idea. I can't promise anything but I'll tag this for AF3.

**Comment by Qix-** [comment]
Hey there, sorry for the delay. I don't think this is something we'll want to support for now, but thanks for the suggestion!

**Comment by Heath123** [comment]
This seems like an important feature for recreating images as ASCII, why not?

**Comment by Heath123** [comment]
I guess I can use the dev tools to add a background image in CSS but that's not ideal
