### ISSUE TITLE
Select+Copy (shortcut) doesn't work

### ISSUE THREAD

**Issue by tobia** [lewish/asciiflow#69]
Maybe I'm missing something, but this would be quite useful

**Comment by Qix-** [comment]
Going to re-purpose this as "select + copy doesn't work" and tag it to make sure it's properly addressed in AF3.

Sorry for the noise 4 years later! :)

**Comment by lewish** [comment]
You can now select, copy and paste in the new release, and this uses the clipboard so you can copy in and out of asciiflow.
