### ISSUE TITLE
RST tables et al are mangled when pasted into Asciiflow

### ISSUE THREAD

**Issue by abulka** [lewish/asciiflow#87]
It would be nice to be able to edit my restructured text tables with this editor.  Unfortunately the needed header ==== and plus + symbols get stripped by asciiflow2 and any resulting tables become incompatible with .rst format.
```
+--+--+--+
|  |  |  |
+==+==+==+
|  |  |  |
+--+--+--+
|  |  |  |
+--+--+--+
|  |  |  |
+--+--+--+
```

gets converted into:

```
+--------+
|  |  |  |
|==|==|==|
|  |  |  |
+--------+
|  |  |  |
+--------+
|  |  |  |
+--------+
```

and also I cannot resize the header area using the asciiflow2 resize tool.

**Comment by Qix-** [comment]
Just some tidying, sorry for the noise 3 years later.

**Comment by Qix-** [comment]
Hey there, this should be fixed now. Let us know if it's not!
