### ISSUE TITLE
Ctrl+Z while drawing an object breaks undo

### ISSUE THREAD

**Issue by openback** [lewish/asciiflow#88]
Steps to reproduce:
* Draw a square
* Start drawing a second square, but do not mouse up yet
* Type `Ctrl+Z` (The first square is undone)
* Mouse up (The second square is drawn)

At this point you're left with your second square, but with no way to undo it. If you also intersect the squares,  the second drawn square will be missing some lines.

**Comment by Qix-** [comment]
Confirmed, amazing catch. Thanks for the reproduction steps.

**Comment by lewish** [comment]
This is fixed now with the latest release!
