### ISSUE TITLE
Keyboard shortcuts for switching between tools

### ISSUE THREAD

**Issue by MohammedNoureldin** [lewish/asciiflow#90]
Hello, thank you for this app, 

I (and a lot of users I am sure) would like to have shortcuts to switch between the tools, for example `e` to choose the eraser, `a` for for arrow, etc... that will save time searching in the toolbar for the keyboard-fan users.

**Comment by Qix-** [comment]
Agreed, I've often found myself wishing for the same :)

**Comment by mort3za** [comment]
Accidentaly found CTRL + Drag can move the background paper. It would be very useful to have a list of keyboard combinations.

**Comment by Qix-** [comment]
@mort3za The ctrl + drag is explained in the top right when you click on the `?` button :)

**Comment by lewish** [comment]
List of keyboard shortcuts now exists in the new version.

Still no shortcuts for the tools, will keep this open for that.

**Comment by ade-sede** [comment]
I tried adding shortcuts for the drawing tools. Here is the [PR](https://github.com/lewish/asciiflow/pull/212) for the interested parties.  
After quick local testing, it seems to be working.

**Comment by theicfire** [comment]
Is this issue intended to still be open?

I also noticed a bug: MacOS uses [alt codes](https://www.webnots.com/option-or-alt-key-shortcuts-to-insert-symbols-in-mac-os-x/) for alt + numbers. These shortcuts don't work for me on AsciiFlow, as a result. For example, alt + 2 is ™.

If I press alt and use my numpad, they work though.

**Comment by wiwo192** [comment]
+100. Having keyboard shortcuts for tool would make ascii super awesome, and productive.

Ideally, the shortcuts would be kept to the left hand keyboard (touch typing), so that users can use the right hand to manipulate the mouse, and left hand to switch tool.

Coincidentally, excalidraw seems to do exactly just this. Finding it super effective, and allows us to draw much quicker. Here are the shortcuts, for reference.

https://imgur.com/a/GOTlMjN

**Comment by ade-sede** [comment]
> +100. Having keyboard shortcuts for tool would make ascii super awesome, and productive.
> 
> Ideally, the shortcuts would be kept to the left hand keyboard (touch typing), so that users can use the right hand to manipulate the mouse, and left hand to switch tool.
> 
> Coincidentally, excalidraw seems to do exactly just this. Finding it super effective, and allows us to draw much quicker. Here are the shortcuts, for reference.
> 
> https://imgur.com/a/GOTlMjN

Shortcuts have been implemented and deployed.
The in-app documentation has been updated as well :tada:.
View shortcuts by pressing `alt`.
Each functionality is bound to `alt-1`, `alt-2`, etc...

Shortcuts with my left hand and drawing on a graphic tablet is exactly how I work with all the whiteboard apps I use :wink:.

**Comment by ade-sede** [comment]
> Is this issue intended to still be open?

I think it should be closed, and further improvement / bug fixing should be moved to other tickets. But I don't really know what's been done so far in term of project management.

WDYT @lewish ?

Maybe you can create a new ticket for this issue, and worst case scenario someone tells us we shouldn't have :see_no_evil: 

> I also noticed a bug: MacOS uses [alt codes](https://www.webnots.com/option-or-alt-key-shortcuts-to-insert-symbols-in-mac-os-x/) for alt + numbers. These shortcuts don't work for me on AsciiFlow, as a result. For example, alt + 2 is ™.
> 
> If I press alt and use my numpad, they work though.

Sorry about that.
I run Linux and don't have a MacOS machine available for testing, so I didn't.

From the documentation you linked and your comment, I am not sure how to correctly flag the right input for `alt-<n>` on Mac.

Do you have an idea on what the condition would look like ?
Here's the commit that enabled the feature for reference: https://github.com/lewish/asciiflow/commit/d69aab7bb2459ab590cd30e2f6658944a88736df

One additional question:  
Does the `cmd` chip display correctly on all shortcut related text ?

**Comment by theicfire** [comment]
The alt codes bug is fixed in https://github.com/lewish/asciiflow/pull/224
